### ISSUE TITLE
你好,请问安装时引导不显示install monterey?

### ISSUE THREAD

**Issue by lijianxiong** [jhihhe/Hackintosh-Asus_Prime_Z390P-i9-9900K_UHD630-RX-6600XT-EFI_OpenCore-0.8.0-macOS#2]
安装的时候只有两个小图标,但是没有显示install monterey请问要怎么设置?

**Comment by jhihhe** [comment]
1.检查Drivers目录有无HfsPlus.efi
2.修改 config.plist：Misc→Security→ScanPolicy→ 0
填写 0 会扫描所有内容并开启所有选项
最新一版已内置HfsPlus.efi，测试可扫描到安装分区

**Comment by lijianxiong** [comment]
> 1.检查Drivers目录有无HfsPlus.efi 2.修改 config.plist：Misc→Security→ScanPolicy→ 0 填写 0 会扫描所有内容并开启所有选项 最新一版已内置HfsPlus.efi，测试可扫描到安装分区

好的感谢你的回复,我下载的是opencore7.9/8.0的版本发现里面没有HfsPlus.efi这个文件,请问是把这个文件放到Drivers就可以了吗?还是要更新config.plist?

**Comment by jhihhe** [comment]
更新config.plist
