### ISSUE TITLE
6600（没有XT）启动之后黑屏怎么办

### ISSUE THREAD

**Issue by yuche** [jhihhe/Hackintosh-Asus_Prime_Z390P-i9-9900K_UHD630-RX-6600XT-EFI_OpenCore-0.8.0-macOS#3]
如果只用 iGPU 可以正常进入系统使用，启动项  `agdpmod` 的几个值都试过了

**Comment by yuche** [comment]
`ResizeAppleGpuBars` 设置为 `8`，`ResizeGpuBars` 为 `0` 就可以了

**Comment by jhihhe** [comment]
> 

升级了OC版本，理论上不需要修改参数了
