### ISSUE TITLE
i7-9700可以只直接使用吗

### ISSUE THREAD

**Issue by okami-chen** [jhihhe/Hackintosh-Asus_Prime_Z390P-i9-9900K_UHD630-RX-6600XT-EFI_OpenCore-0.8.0-macOS#5]
除了CPU其他都一样，集成显卡，可以直接使用吗

**Comment by jhihhe** [comment]
https://github.com/jhihhe/Asus-Prime-Z390P-i9-9900K-UHD630-RX-6600XT-Hackintosh/releases/download/230104/EFI20230104088a-IGPU.zip

**Comment by jhihhe** [comment]
> 除了CPU其他都一样，集成显卡，可以直接使用吗

https://github.com/jhihhe/Asus-Prime-Z390P-i9-9900K-UHD630-RX-6600XT-Hackintosh/releases/download/240209/EFI2024009041.01a-IGPU.zip

**Comment by jhihhe** [comment]
> 除了CPU其他都一样，集成显卡，可以直接使用吗

更新了IGPU版本

**Comment by okami-chen** [comment]
oc最新1.0.1，当前版本OC支持最新版本的14.6.1吗

**Comment by jhihhe** [comment]
> oc最新1.0.1，当前版本OC支持最新版本的14.6.1吗

支持
博通网卡需自行配置OCLP:
https://bbs.pcbeta.com/viewthread-1992658-1-1.html
https://github.com/dortania/OpenCore-Legacy-Patcher/releases

**Comment by okami-chen** [comment]
14系统前，博通网卡是免驱，不用额外配置，直接使用你的EFI就行，可能需要定制USB是吧

**Comment by okami-chen** [comment]
没有清楚nvram选项

**Comment by okami-chen** [comment]
开机没有背景图片，只有文字选项可以选

**Comment by jhihhe** [comment]
> 没有清楚nvram选项

先查询OC说明搞清OC怎么使用,这边不是软件售后
